### ISSUE TITLE
Doesn't build with dmd 2.087.0

### ISSUE THREAD

**Issue by John-Colvin** [ariovistus/pyd#115]
```
 ~/Git/pyd (git)-[master] % dub build
Performing "debug" build using /home/john/dlang/dmd-2.087.0/linux/bin64/dmd for x86_64.
pyd 0.10.4+commit.8.gd21f7c3: building configuration "python27"...
infrastructure/util/multi_index.d(4905,5): Error: class allocators are obsolete, consider moving the allocation strategy outside of the class
infrastructure/util/multi_index.d(4909,5): Error: class deallocators are obsolete, consider moving the deallocation strategy outside of the class
infrastructure/util/multi_index.d(4042,5): Error: class allocators are obsolete, consider moving the allocation strategy outside of the class
infrastructure/util/multi_index.d(4046,5): Error: class deallocators are obsolete, consider moving the deallocation strategy outside of the class
infrastructure/util/multi_index.d(3551,26): Error: template instance `util.multi_index.Position!(MNode!(MultiIndexContainer!(Thread, IndexedBy!(__T6HashedVbi0VAyaa1_61VQja21_7479706569642861292e6765744861736828266129VQCga4_613d3d62Z), MallocAllocator, MutableView), IndexedBy!(__T6HashedVbi0VAyaa1_61VQja21_7479706569642861292e6765744861736828266129VQCga4_613d3d62Z), MallocAllocator, Inner!(IndexedBy!(__T6HashedVbi0VAyaa1_61VQja21_7479706569642861292e6765744861736828266129VQCga4_613d3d62Z)), Thread, Thread))` error instantiating
infrastructure/pyd/thread.d(31,19):        instantiated from here: MultiIndexContainer!(Thread, IndexedBy!(__T6HashedVbi0VAyaa1_61VQja21_7479706569642861292e6765744861736828266129VQCga4_613d3d62Z), MallocAllocator, MutableView)
infrastructure/util/multi_index.d-mixin-4978(4981,21): Error: mixin `util.multi_index.MultiIndexContainer!(Thread, IndexedBy!(__T6HashedVbi0VAyaa1_61VQja21_7479706569642861292e6765744861736828266129VQCga4_613d3d62Z), MallocAllocator, MutableView).MultiIndexContainer.IndexMixin!(0LU, "a", "typeid(a).getHash(&a)", "a==b", false, SequencedRange, MultiIndexContainer!(Thread, IndexedBy!(__T6HashedVbi0VAyaa1_61VQja21_7479706569642861292e6765744861736828266129VQCga4_613d3d62Z), MallocAllocator, MutableView))` error instantiating
/home/john/dlang/dmd-2.087.0/linux/bin64/dmd failed with exit code 1.
```

**Comment by burner** [comment]
after removing the allocators from the code dmd dies on me.

**Comment by John-Colvin** [comment]
https://issues.dlang.org/show_bug.cgi?id=20056

**Comment by burner** [comment]
a fix has been already pulled into dmd-stable

**Comment by burner** [comment]
https://github.com/ariovistus/pyd/pull/116
